// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/ajayjadhav201/golang-templ/view/layout"

func SignupPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"min-h-screen flex items-center justify-center bg-blue-400\"><div class=\"bg-white p-16 rounded shadow-2x1 w-1/2\"><h2 class=\"text-3xl font-bold mb-10 text-gray-800\">Create Your Account</h2><form class=\"space-y-5\"><div><label class=\"block mb-1 font-bold text-gray-500\">Name</label> <input type=\"text\" class=\"w-full border-2 border-gray-200 p-3 rounded outline-none focus:border-purple-500\"></div><div><label class=\"block mb-1 font-bold text-gray-500\">Email</label> <input type=\"email\" class=\"w-full border-2 border-gray-200 p-3 rounded outline-none focus:border-purple-500\"></div><div><label class=\"block mb-1 font-bold text-gray-500\">Password</label> <input type=\"password\" class=\"w-full border-2 border-gray-200 p-3 rounded outline-none focus:border-purple-500\"></div><div class=\"flex items-center\"><input type=\"checkbox\" id=\"agree\"> <label for=\"agree\" class=\"ml-2 text-gray-700 text-sm\">I agree to the terms and privacy.</label></div><div><button class=\"block w-full bg-yellow-400 hover:bg-yellow-300 p-4 rounded text-yellow-900 hover:text-yellow-800 transition duration-300\">Sign Up</button></div></form></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
